# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['stash-away.py', 'stash_away_tui.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'rich',
        'rich.console', 
        'rich.table', 
        'rich.panel',
        'rich.layout',
        'rich.live',
        'rich.prompt',
        'rich.text',
        'rich.align',
        'rich.box',
        'rich.control',
        'rich.segment',
        'rich._emoji_codes',
        'rich._emoji_replace',
        'rich.pretty',
        'rich.traceback',
        'rich.logging',
        'rich.tree',
        'rich.columns',
        'rich.syntax',
        'markdown_it',
        'markdown_it.rules_block',
        'markdown_it.rules_inline',
        'markdown_it.rules_core',
        'markdown_it.renderer',
        'markdown_it.ruler',
        'markdown_it.token',
        'mdurl'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='stash-away',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)